function logfile = readPhysLog(filename, dataLines)
%IMPORTFILE Import data from Philips physlog file *.log
%  logfile = readPhysLog(FILENAME) reads data from
%  text file FILENAME for the default selection.  Returns the data as a
%  table.
%
%  LOGFILE = READPHYSLOG(FILE, DATALINES) reads data
%  for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  logfile = readPhysLog("/srv/data/scratch/data_test/PHYSLOG/ScanPsaLog20220927095214_SE11.log", [5, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 28-Nov-2022 14:18:47

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [5, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 12);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = [" ","#"];

% Specify column names and types
opts.VariableNames = ["v1raw", "v2raw", "v1", "v2", "ppu", "resp", "vsc", "gx", "gy", "gz", "mark", "mark2"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Import the data
logfile = readtable(filename, opts);

end